os: osx
language: objective-c
osx_image: xcode10.2

git:
  depth: 1

# Use new container infrastructure to enable caching
#rvm: 2.5.0

jobs:
  include:
    - stage: "Build"
      name: "Build Rome & Test Dymanic Frameworks"
      before_install:
        - rvm mount http://rubies.travis-ci.org/osx/10.14/x86_64/ruby-2.5.0.tar.bz2 --verify-downloads 2
        # Update Homebrew
        - brew update
        # Run bundler and install the dependencies in vendor/bundle
        # so that it can be cached.
        - bundle install --deployment 
      install:
        # Install stack
        - mkdir -p ~/.local/bin
        - export PATH=$HOME/.local/bin:$PATH
        - brew install stack

        # Download and instal hlint
        - rake hlint:install[2.1.16]

        # Download and install minio
        - travis_retry wget -O $HOME/.local/bin/minio https://dl.minio.io/server/minio/release/darwin-amd64/minio || echo "Minio already in cache"
        - chmod +x $HOME/.local/bin/minio

        # Install Carthage
        - brew outdated carthage || brew upgrade carthage

        # Install bats-core
        - brew install bats-core
      script:
        - bundle exec danger
        - stack $ARGS setup -j 2
        - stack $ARGS test --no-terminal --haddock --no-haddock-deps
        - stack $ARGS build -j 2
        - stack $ARGS sdist
        - stack $ARGS install
        - travis_wait 60 bats integration-tests/dynamic-frameworks-ini.bats
        - travis_wait 60 bats integration-tests/dynamic-frameworks-yml.bats
        - travis_wait 60 bats integration-tests/dynamic-frameworks-engine-yml.bats
    - stage: "Build"
      name: "Build Rome & Test Current Frameworks"
      before_install:
        - rvm mount http://rubies.travis-ci.org/osx/10.14/x86_64/ruby-2.5.0.tar.bz2 --verify-downloads 2
        # Update Homebrew
        - brew update
        # Run bundler and install the dependencies in vendor/bundle
        # so that it can be cached.
        - bundle install --deployment 
      install:
        # Install stack
        - mkdir -p ~/.local/bin
        - export PATH=$HOME/.local/bin:$PATH
        - brew install stack

        # Download and instal hlint
        - rake hlint:install[2.1.16]

        # Download and install minio
        - travis_retry wget -O $HOME/.local/bin/minio https://dl.minio.io/server/minio/release/darwin-amd64/minio || echo "Minio already in cache"
        - chmod +x $HOME/.local/bin/minio

        # Install Carthage
        - brew outdated carthage || brew upgrade carthage

        # Install bats-core
        - brew install bats-core
      script:
        - bundle exec danger
        - stack $ARGS setup -j 2
        - stack $ARGS test --no-terminal --haddock --no-haddock-deps
        - stack $ARGS build -j 2
        - stack $ARGS sdist
        - stack $ARGS install
        - travis_wait 60 bats integration-tests/current-framework-yml.bats
        - travis_wait 60 bats integration-tests/current-framework-engine-yml.bats
        - travis_wait 60 bats integration-tests/current-framework-named-yml.bats
        - travis_wait 60 bats integration-tests/current-framework-named-engine-yml.bats
    - stage: "Build"
      name: "Build Rome & Test Static Frameworks"
      before_install:
        - rvm mount http://rubies.travis-ci.org/osx/10.14/x86_64/ruby-2.5.0.tar.bz2 --verify-downloads 2
        # Update Homebrew
        - brew update
        # Run bundler and install the dependencies in vendor/bundle
        # so that it can be cached.
        - bundle install --deployment 
      install:
        # Install stack
        - mkdir -p ~/.local/bin
        - export PATH=$HOME/.local/bin:$PATH
        - brew install stack

        # Download and instal hlint
        - rake hlint:install[2.1.16]

        # Download and install minio
        - test ! -e $HOME/.local/bin/minio && travis_retry wget -O $HOME/.local/bin/minio https://dl.minio.io/server/minio/release/darwin-amd64/minio || echo "Minio already in cache"
        - chmod +x $HOME/.local/bin/minio

        # Install Carthage
        - brew outdated carthage || brew upgrade carthage

        # Install bats-core
        - brew install bats-core
      script:
        - bundle exec danger
        - stack $ARGS setup -j 2
        - stack $ARGS test --no-terminal --haddock --no-haddock-deps
        - stack $ARGS build -j 2
        - stack $ARGS sdist
        - stack $ARGS install
        - travis_wait 60 bats integration-tests/static-frameworks-ini.bats
        - travis_wait 60 bats integration-tests/static-frameworks-yml.bats
        - travis_wait 60 bats integration-tests/static-frameworks-engine-yml.bats

env:
- ARGS="--resolver=lts-14.14"

cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work
  - vendor/bundle
